version: 2.1

orbs:
  slack: circleci/slack@4.13.2
  rust: circleci/rust@1.6.1

jobs:
  build-slack:
    docker:
      - image: cimg/rust:1.60.0
    working_directory: ~/select-con
    steps:
      - checkout
      - run:
          name: build
          command: cargo build
      - run:
          name: run
          command: |
            TEXT=`cargo run -q`
            echo "export TEXT_MESSAGE='${TEXT}'" >> $BASH_ENV
      - run:
          command: echo "${TEXT_MESSAGE}"
      - slack/notify:
          channel: ${SLACK_CHANNEL}
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Todays AtCoder",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${TEXT_MESSAGE}>"
                  }
                }
              ]
            } 

workflows:
  version: 2
  build:
    jobs:
      - build-slack:
          context: slack-secrets
