version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  rust: circleci/rust@1.6.0

jobs:
  build-slack:
    docker:
      - image: cimg/base:stable
    working_directory: ~/select-con
    steps:
      - checkout
      - rust/build
      - run:
          name: run
          command: |
            TEXT=`cargo run -q`
            echo "export TEXT_MESSAGE='${TEXT}'" >> $BASH_ENV
      - run:
          command: echo "${TEXT_MESSAGE}"
      - slack/notify:
          channel: ${SLACK_CHANNEL}
          color: '#42e2f4'
          message: "${TEXT_MESSAGE}"
          webhook: ${SLACK_WEBHOOK}

workflows:
  version: 2
  build:
    jobs:
      - build-slack
