version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  rust:
    docker:
      - image: circleci/rust

jobs:
  build-slack:
    executor: rust
    working_directory: ~/select-con
    steps:
      - checkout
      - run:
          name: build
          command: cargo build
      - run:
          name: run
          command: |
            TEXT=`cargo run -q`
            echo "export TEXT_MESSAGE='${TEXT}'" >> $BASH_ENV
      - run:
          command: echo "${TEXT_MESSAGE}"
      - slack/notify:
          channel: ${SLACK_CHANNEL}
          color: '#42e2f4'
          message: "${TEXT_MESSAGE}"
          webhook: ${SLACK_WEBHOOK}

workflows:
  version: 2
  build:
    jobs:
      - build-slack
  nightly_workflow:
    triggers:
      - schedule:
          cron: "0 11 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-slack
