version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  default:
    docker:
      - image: circleci/rust

jobs:
  build-slack:
    executor: 'default'
    steps:
      - 'checkout'
      - run:
        name: build
        command: cargo build
      - run:
        name: run
        command: |
          text=`cargo run -q`
          echo 'export TEXT_MESSAGE=${test}' >> $BASH_ENV
      - run:
          command: echo ${TEXT_MESSAGE}
      - slack/notify:
          channel: ${SLACK_CHANNEL}
          color: '#42e2f4'
          message: ${TEXT_MESSAGE}
          webhook: ${SLACK_WEBHOOK}
